[package]
name = "niobe"
version = "0.0.0"
edition = "2018"
description = "Data visualization library"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
